### ISSUE TITLE
Shopware 5.7.1 - whiteout

### ISSUE THREAD

**Issue by shopmeister** [FriendsOfShopware/FroshAdminer#10]
if installing it into the new shopware 5.7.1 version, its shoing only a whitepage after opening the menue tab.
no entrys in the console log.

PHP Error:
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "shopware.app.rootdir" must be defined. in

**Comment by shyim** [comment]
Has been fixed with https://github.com/FriendsOfShopware/FroshAdminer/commit/e9fd484ad92508da50bbb7a0a01ffbbfcf4559a6
