### ISSUE TITLE
new Release ?

### ISSUE THREAD

**Issue by ghost** [FriendsOfShopware/FroshAdminer#12]
### Question

Could you please release a new version that is more like actual master branch? Because in current shopware version plugin stops working because of case sensitivity bug in Admin controller where the latest release (1.3.4) reads **shopware.app.rootdir**
instead of correct **shopware.app.rootDir** in master leading to errors for those relying on zip file i.e. for production environments.

Gracias

**Comment by shyim** [comment]
I will release it tonight sorry

**Comment by shyim** [comment]
fixed with https://github.com/FriendsOfShopware/FroshAdminer/releases/tag/1.3.5
