### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by ottscho** [FriendsOfShopware/FroshAdminer#13]
### PHP Version

PHP8

### Shopware Version

5.6.7

### Actual behaviour

https://www.php.net/get_magic_quotes_gpc

Warning
This function has been DEPRECATED as of PHP 7.4.0, and REMOVED as of PHP 8.0.0. Relying on this function is highly discouraged.

### Expected behaviour

see https://github.com/FriendsOfShopware/FroshAdminer/blob/master/Adminer/Adminer.php#L20

### Steps to Reproduce?

open Adminer under PHP8

**Comment by shyim** [comment]
fixed with https://github.com/FriendsOfShopware/FroshAdminer/releases/tag/1.3.6
