### ISSUE TITLE
Access Array Fehler an allen möglichen Stellen

### ISSUE THREAD

**Issue by Wachert** [FriendsOfShopware/FroshAdminer#14]
### PHP Version

8.3

### Shopware Version

6.5.8.2

### Plugin Version

1.0.1

### Actual behaviour

Beim Aufruf diverser Tabellen wirft der Adminer immer diverse dieser Fehler:
Warning: Trying to access array offset on null in /var/www/sw6/custom/plugins/FroshPlatformAdminer/src/Adminer/Adminer.php on line 549

### Expected behaviour

Kein Fehler :D

### Steps to Reproduce?

z.B. Tabelle sales_channel aufrufen

Hinweis: mysql-server-8.0              8.0.35-0ubuntu0.22.04.1

**Comment by shyim** [comment]
We have fixed that with https://github.com/FriendsOfShopware/FroshPlatformAdminer/releases/tag/2.0.0
