### ISSUE TITLE
Typos in README (?)

### ISSUE THREAD

**Issue by crydotsnake** [FriendsOfShopware/FroshAdminer#8]
Good Evening!,

In the README at `ElasticSearch` and `MySQL`, it says `Adminer in Shopware` and Redirects to `https://camo.githubusercontent.com/99b8c6453f2ef79c08d8b946854a7dc462b0c75c/68747470733a2f2f697066732e696f2f697066732f516d55706a4d4245484d37546f32683957557445326446484d44784e41373738565333464d327045745957474a34` But on the URL it says `Error Fetching Resource`.. What exactly goes into those two sections?. I would really love to fix it for you, but ive no idea what goes into this two sections in the readme..

**Comment by shyim** [comment]
That image was in ipfs. Seems down. Will replace it tomorrow

**Comment by crydotsnake** [comment]
Ah, okay !^^

**Comment by shyim** [comment]
Fixed!

**Comment by crydotsnake** [comment]
Thanks !😊
