### ISSUE TITLE
refused to connect Error

### ISSUE THREAD

**Issue by rawdlite** [FriendsOfShopware/FroshAdminer#9]
i am running the plugin on shopware 5.6.9 against an aws aurora mysql 5.7 DB.
On one of my instances i get an "<shopname> refused to connect." error in the BE.
On the other instances the plugin works flawlessly.
For testing i put an adminer.php file in the document root of the faulty instance.
This way i can connect to the database entering the credentials.
Then i did grep FroshAdminer /var/log/apache2/access.log and used the custom plugins FroshAdminer URL i found there.
This also opens the database.
Now i have run out of ideas why i cant use the plugin in the shopware BE.
Any pointers appreciated.

**Comment by shyim** [comment]
maybe something special in database configuration idk.

**Comment by rawdlite** [comment]
If it is the database configuration would that not also be an issue where connecting with the admirer.php in document root?

**Comment by shyim** [comment]
The plugin tries to connect by config.php by default. When you have an special configuration maybe the auto login does not work.

Does the normal login work?

**Comment by rawdlite** [comment]
Thank you for looking into this.
Normal login to the shop works.
Login into the DB via an external admirer.php file works.
Plugins just says 'refused to connect'. No way to do a manual connect after that.
The actual database credentials are stored in an .env file.
This is the result of a setup by composer.
In app/config/config.php this gets evaluated by

```
if (getenv('DATABASE_URL') && $db = parse_url(getenv('DATABASE_URL'))) {
    $db = array_map('rawurldecode', $db);
    $db['path'] = substr($db['path'], 1);
    if (!isset($db['pass'])) {
        $db['pass'] = '';
    }
```
So it seems to me the Plugin is not getting the Environment Variable DATABASE_URL or an outdated version of it.
The Database URL has changed recently.
Is there an easy way to see value of DATABASE_URL the plugin is using?
The error message in the Frontend is just "xxxx refused to connect". It would be helpful when the Value of DATABASE_URL Variable that the Plugin is actually seeing could be displayed here.
I am beginning wonder whether this might be an issue of different php-fpm pools being used by shop and plugin.

**Comment by shyim** [comment]
You could dump here :)
https://github.com/FriendsOfShopware/FroshAdminer/blob/master/Controllers/Backend/Adminer.php#L34

**Comment by rawdlite** [comment]
I did a var_dump and the values i see for database, server, user and password are correct.
The other variables I see look good too.
```
["charset"]=> string(7) "utf8mb4" 
["timezone"]=> NULL 
["adapter"]=> string(9) "pdo_mysql" 
["pdoOptions"]=> NULL 
["serverVersion"]=> NULL 
["defaultTableOptions"]=> array(2) { ["charset"]=> string(4) "utf8" ["collate"]=> string(15) "utf8_unicode_ci" } ["session"]=> array(0) { } }
```

Yet the plugin does not connect.

**Comment by rawdlite** [comment]
Solved it.
The Error resulted from a faulty X-Frame-Options entry.

**Comment by rawdlite** [comment]
To elaborate on the problem:
in .htaccess the directive 'Header set X-Frame-Options: "ALLOW-FROM http://webvisor.com"'
Then in Adminer/plugins/AdminerFrames.php  X-Frame-Options gets set to same origin.
Now we have 2 conflicting  X-Frame-Options and it gets set to deny.
Not sure how to solve this.

**Comment by shyim** [comment]
Thats not really possible as the webservers wins. I will close this then
